### ISSUE TITLE
Hello,I met some trouble , mAP is zero

### ISSUE THREAD

**Issue by Mahiro2211** [JalinWang/DCGH#1]
Thanks for sharing the code, but when I tested it on my computer it seemed to be some error
![image](https://github.com/JalinWang/DCGH/assets/130811701/61318217-e91a-4a6a-bd56-0cb6204d6aa7)

**Comment by Mahiro2211** [comment]
I tried to change the evaluate function, and it can work, but still have to make an effort on finding nice settings of paramerters

**Comment by JalinWang** [comment]
https://github.com/JalinWang/DCGH/blob/422bdc3b9e252e9d92d979b0edf1286268a2535a/main.py#L166-L181

1 iter is not enough for evaluation. You can try to decrease `args.eval_iter` or increase the number of iterations

**Comment by Mahiro2211** [comment]
Thanks a lot
